### ISSUE TITLE
The testimony block bottom is distorted.

### ISSUE THREAD

**Issue by shinde-rahul** [mautic/mautic-website#11]
The testimony block has margin issues; 

![Image](https://github.com/user-attachments/assets/ae031992-9bfe-4567-a474-9e6e1d438a81)

I tried with the following style change,
```css
.elementor-13 .elementor-element.elementor-element-711c499 {
    --display: flex;
    --padding-top: 0px;
    --padding-bottom: 35px;
    --padding-left: 20px;
    --padding-right: 20px;
}
```
This translates to UI as this,

![Image](https://github.com/user-attachments/assets/f54a621d-e8e7-4c50-9a6a-f52acea1d03f)

Another issue is that I see huge gaps between blocks—a total of 280px. Can we make this shorter? I am not sure what the repercussions will be.

```css
.elementor-13 .elementor-element.elementor-element-7f52cbf {
    --display: flex;
    --flex-direction: column;
    --container-widget-width: 100%;
    --container-widget-height: initial;
    --container-widget-flex-grow: 0;
    --container-widget-align-self: initial;
    --flex-wrap-mobile: wrap;
    --margin-top: 140px;
    --margin-bottom: 140px;
    --margin-left: 0px;
    --margin-right: 0px;
    --padding-top: 0px;
    --padding-bottom: 0px;
    --padding-left: 0px;
    --padding-right: 0px;
}
```
